### PR TITLE
fixes #108 button start slot margin issue fixed

### LINKED ISSUE #108: Button start slot without content shows margin
Svelte doesn't support conditional slots. So, in apps we cannot do this:

```svelte
<Button>
    {#if loading}<Loader slot="start" />{/if}
</Button>
```

The only solution is to wrap the loader:

```svelte
<Button>
     <span slot="start">{#if loading}<Loader  />{/if}</span>
</Button>
```

But, when the loader is not there, the `<Button>` element shows a margin (because the slot is set, even its empty)

image

Maybe check CSS `:empty`?

### PR DESCRIPTION
**Pull request by IshiniAvindya**
button start slot margin issue fixed

### CODE REVIEW

**Comment by supun-io** [comment]
Clean up the commented code

File: src/routes/(docs)/[[slug]]/docs/Button.svelte [hunk 1]
```diff
@@ -349,7 +352,21 @@ All other properties will be forwarded to the underlying element.
     </Button>
 </CodeResult>
 
-<!--Code example for disabled button -->
+
+<h3>Conditional Buttons</h3>
```
Comment (supun-io) [inline src/routes/(docs)/[[slug]]/docs/Button.svelte:356]: This shoud be "Conditional slots"

Comment (supun-io) [reply src/routes/(docs)/[[slug]]/docs/Button.svelte:356]: @IshiniAvindya
